node_id: node-2
http_addr: ":8081"
raft_addr: ":9081"
admin_addr: ":7081"
log_level: info
data_dir: ./data/cluster/node-2
peers:
  - id: node-1
    raft_addr: "localhost:9080"
  - id: node-3
    raft_addr: "localhost:9082"
